spring:
  application:
    name: BVT_demo
  datasource:
    #jdbc:mysql://localhost:3306/{your_db_name}
    url: jdbc:postgresql://localhost:5432/sandbox
    username: postgres
    password: ${PSQL_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8080
